name: Run Python Scripts

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    name: Run Python Script
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Run Python Script
        run: python main.py
